### ISSUE TITLE
Assignments From [ 010 ] To [ 017 ]/Assignment 4.js 

### ISSUE THREAD

**Issue by abdelrahman48** [PhilopaterHany/JavaScript-Bootcamp#1]
الحل كده مش زي ما هو طلب 
هو طلب عدم تكرار المتغيرات
والكود بتاعك يتكتب جوا الكونسول فقط
![image](https://user-images.githubusercontent.com/43393558/140787483-16503594-379b-4be4-af96-b7d1d056b1bc.png)

**Comment by PhilopaterHany** [comment]
شكرا علي التنبيه
تم التعديل و ضفت الاجابة الصحيحة
