### ISSUE TITLE
`${word}`

### ISSUE THREAD

**Issue by idriss112** [PhilopaterHany/JavaScript-Bootcamp#11]
https://github.com/PhilopaterHany/JavaScript-Bootcamp/blame/6800e75d30a63bf1330d83b148841725bb16c651/Assignments/Assignments%20From%20%5B%20094%20%5D%20To%20%5B%20101%20%5D/Assignment%203/master.js#L10

**Comment by PhilopaterHany** [comment]
Fixed.
Thank you ♥️
