### ISSUE TITLE
Assignments From [ 054 ] To [ 056 ] Loop Challenge.js

### ISSUE THREAD

**Issue by abdelrahman48** [PhilopaterHany/JavaScript-Bootcamp#7]
لو شيلنا "الاستوب"  من المصفوفه الكود مش هيشتغل
 انا عارف انها حاجه مش مطلوبه فالتحدي بس انت دايما بعد ما تخلص اي تكليف اقعد جرب وشوف الكود دينامك ولا لأه وحاول تخليه دينامك
[https://github.com/PhilopaterHany/JavaScript-Bootcamp/blob/main/Assignments/Assignments%20From%20%5B%20054%20%5D%20To%20%5B%20056%20%5D/Loop%20Challenge.js](url)

**Comment by PhilopaterHany** [comment]
تمام 
تم التعديل و اضافة الحل الصحيح
شكرا لك
